version: 0.2

phases:
  install:
   runtime-versions:
     nodejs: 12
   commands:
     - echo "Setting up node"
  pre_build:
   commands:
    - echo "Installing dependencies"
     - npm install
  build:
    commands:
      - echo "Building app/running tests"
      # - npm test
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'