---
AWSTemplateFormatVersion: '2010-09-09'
# Parameters:
#   ArtifactBucket:
#     Type: String
#     Description: Name of S3 bucket
Resources:
  HelloWorld:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorld
      Handler: index.handler
      Role: !GetAtt HelloWorldLambdaRole.Arn
      # Code:
      #   S3Bucket: !Sub ${ArtifactBucket}
      #   S3Key: hello-world.zip
      PackageType: Zip
      Code: ./src/
      Runtime: python3.12
  HelloWorldLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HelloWorldLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: AWSLambdaBasicExecutionRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
